spring.application.name=morphol
spring.datasource.url=jdbc:mysql://localhost:3306/turkish_morphology_builder
spring.datasource.username=root
spring.datasource.password=12_34*BoR123321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true